gym/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('plataforma.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plataforma/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('home/', views.home, name='home'),
    path('aluno/<int:id>/', views.aluno, name='aluno'),

    #CRUD ALUNOS
    path('alunos/', views.alunos, name='alunos'),
    path('cadastro_aluno/', views.cadastro_aluno, name='cadastro_aluno'),
    path('deletar_aluno/<int:id>/', views.deletar_aluno, name='deletar_aluno'),
    path('dados_aluno/<int:id>/', views.dados_aluno, name='dados_aluno'),
    path('editar_aluno/<int:id>/', views.editar_aluno, name='editar_aluno'),

    #FICHA DE TREINO
    path('ficha_treino/', views.ficha_treino, name='ficha_treino'),
    path('ficha_treino_id/<int:id>/', views.ficha_treino_id, name='ficha_treino_id'),


    path('grupos/', views.grupos, name='grupos'),
    path('grupo/<int:id>/', views.grupo, name='grupo'),
 
    #CRUD EXERCICIOS
    # BANCO DE EXERCICIO
    path('cadastro_exercicio/', views.cadastro_exercicio, name='cadastro_exercicio'),

    # EXERCICIO FICHA
    path('cadastro_exercicio_ficha/', views.cadastro_exercicio_ficha, name='cadastro_exercicio_ficha'),
    path('deletar_exercicio_ficha/<int:id>/', views.deletar_exercicio_ficha, name='deletar_exercicio_ficha'),


    #CRUD TREINO
    path('cadastro_treino/', views.cadastro_treino, name='cadastro_treino'),
]

plataforma/models.py
from django.db import models
from datetime import date

# Create your models here.
class Aluno(models.Model):
    choices_sexo = (('F', 'Feminino'),
    ('M', 'Maculino'))

    nome = models.CharField(max_length=50)
    sexo = models.CharField(max_length=1, choices=choices_sexo)
    data_nascimento = models.DateField()
    email = models.EmailField()
    telefone = models.CharField(max_length=19)
    # personal = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome

class Avaliacao(models.Model):
    paciente = models.ForeignKey(Aluno, on_delete=models.CASCADE)
    data = models.DateTimeField()
    peso = models.IntegerField()
    altura = models.IntegerField()

    def __str__(self) -> str:
        return f'Dados: {self.paciente} - {self.peso}'




class GrupoMuscular(models.Model):
    nome = models.CharField(max_length=30)
    def __str__(self) -> str:
        return self.nome

class BancoExercicios(models.Model):
    nome = models.CharField(max_length=25)
    grupo_muscular = models.ForeignKey(GrupoMuscular, on_delete=models.SET_NULL, null=True)
    
    def __str__(self):
        return self.nome

class Treino(models.Model):
    aluno = models.ForeignKey(Aluno, on_delete=models.CASCADE)
    nome = models.CharField(max_length=20)
     

    def __str__(self) -> str:
        return self.nome


class Exercicio(models.Model):
    exercicio = models.ForeignKey(BancoExercicios, on_delete=models.SET_NULL, null=True)
    treino = models.ForeignKey(Treino, on_delete=models.CASCADE)
    series = models.CharField(max_length=10)
    tecnica = models.CharField(max_length=25, null=True, blank=True)


    def __str__(self):
        return f'{self.exercicio}'



    


plataforma/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from django.shortcuts import get_object_or_404
from django.contrib.messages import constants
from django.contrib import messages

def home(request):
    return render(request, 'home.html')

# CRUD ALUNOS

def alunos(request):
    alunos = Aluno.objects.all()
    return render(request, 'alunos.html', {'alunos':alunos})

def cadastro_aluno(request):

    if request.method == 'GET':

        return redirect('/alunos/')
    elif request.method == 'POST':
        nome = request.POST.get('nome')
        sexo = request.POST.get('sexo')
        nascimento = request.POST.get('nascimento')
        email = request.POST.get('email')
        telefone = request.POST.get('telefone')
      
        try:
            novo_aluno = Aluno(nome=nome,sexo=sexo,data_nascimento=nascimento,email=email, telefone=telefone)
            novo_aluno.save()
            messages.add_message(request,constants.SUCCESS,'Aluno cadastrado com sucesso!')
            return redirect('/alunos/')
        except Exception as e:
            print(e)
            messages.add_message(request,constants.ERROR,'Erro ao cadastrar aluno!')

            return redirect('/alunos/')


def editar_aluno(request,id):
    if request.method == 'POST':
        try:
                
            aluno = Aluno.objects.get(id=id)

            nome = request.POST.get('nome')
            sexo = request.POST.get('sexo')
            nascimento = request.POST.get('nascimento')
            email = request.POST.get('email')
            telefone = request.POST.get('telefone')
            
            aluno.nome = nome
            aluno.sexo = sexo
            aluno.data_nascimento = nascimento
            aluno.email = email
            aluno.telefone = telefone

            aluno.save()
            return redirect(f'/dados_aluno/{id}')
        except Exception as e:
            print(e)
            return redirect(f'/dados_aluno/{id}')

def dados_aluno(request, id):
    aluno = get_object_or_404(Aluno, id=id)

    return render(request, 'dados_aluno.html',{'aluno':aluno})

def aluno(request, id):
    aluno = get_object_or_404(Aluno, id=id)

    return render(request, 'teste.html',{'aluno':aluno})




def deletar_aluno(request, id):
    aluno = get_object_or_404(Aluno, id=id)
    aluno.delete()
    return redirect('/alunos/')


# CRUD CADASTRO EXERCICIOS

def cadastro_exercicio(request):
    if request.method == 'POST':
        exercicio = request.POST.get('exercicio')
        musculo = request.POST.get('musculo')
        
        grupo_muscular = GrupoMuscular.objects.get(id=musculo)

        novo_exercicio = BancoExercicios(nome=exercicio,grupo_muscular=grupo_muscular)

        novo_exercicio.save()
        return redirect(f'/grupo/{musculo}')


def cadastro_treino(request):
    if request.method == 'POST':
        aluno = request.POST.get('aluno')
        treino = request.POST.get('treino')

        al = Aluno.objects.get(id=aluno)

        novo_treino = Treino(aluno=al, nome=treino)
        novo_treino.save()
        return redirect(f'/ficha_treino_id/{aluno}')


# CRUD CADASTRO EXERCICIOS FICHA ALUNO

def cadastro_exercicio_ficha(request):
    if request.method == 'POST':
        exercicio = request.POST.get('exercicio')
        treino = request.POST.get('treino')
        series = request.POST.get('series')
        tecnica = request.POST.get('tecnica')

    exe = BancoExercicios.objects.get(id=exercicio)
    treino = Treino.objects.get(id=treino)

    novo_exercicio = Exercicio(exercicio=exe, treino=treino, series=series, tecnica=tecnica)

    novo_exercicio.save()
    return redirect(f'/ficha_treino_id/{treino.aluno_id}')

def deletar_exercicio_ficha(request, id):
    exe = Exercicio.objects.get(id=id)

    id_aluno = exe.treino.aluno.id
    

    exe.delete()
    return redirect(f'/ficha_treino_id/{id_aluno}')


def grupos(request):
    grupos = GrupoMuscular.objects.all()
    return render(request, 'grupos.html', {'grupos': grupos})

def grupo(request, id):
    exercicios = BancoExercicios.objects.filter(grupo_muscular_id=id)
    i = GrupoMuscular.objects.get(id=id)
    return render(request, 'grupo_id.html', {'exercicios':exercicios, 'i':i})


# def exercicio(request,id):
#     exercicios = BancoExercicios.objects.filter(grupo_muscular_id=id)
#     return render(request, 'exercicios.html',{'exercicios':exercicios})



def ficha_treino(request):
    alunos = Aluno.objects.all()
    return render(request, 'ficha_treino.html', {'alunos': alunos})


def ficha_treino_id(request, id):
    aluno = get_object_or_404(Aluno, id=id)
    if request.method == 'GET':
    
        treinos = Treino.objects.filter(aluno=aluno)

        exercicios = Exercicio.objects.all()

        banco_exe = BancoExercicios.objects.all()

        return render(request, 'ficha_treino_id.html', {'aluno':aluno, 'treinos': treinos, 'exercicios':exercicios, 'banco_exe': banco_exe})

plataforma/templates/alunos.html
{% extends 'base.html' %}

{% block titulo %}
ALUNOS
{% endblock titulo %}

{% block conteudo %}
<div class="wrapper">
    <div class="box"> 
        <div class="header-box">
            {% if messages %}
                {% for message in messages %}
                    <section class="alert {{message.tags}}">
                        {{message}}
                    </section>
                {% endfor %}
            {% endif %}
       
            <div class='row cd-aluno'>

                <div class='col-md'>
                    <h2 class="titulo">ALUNOS</h2>

                </div>
                <div class='col-md'>
                    <button type="button" class="btn-confirmar" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                        CADASTRAR ALUNO
                      </button>
                

                </div>
            </div>
        </div>
        <div class="borda-box"></div>
        <div class="body-box">
        
            <form action='#' method='GET'> {% csrf_token %}
            <div class="row">
                
                    <div class="col-md-5">
                        <input type="text" placeholder="Busque pelo nome" class="form-control" name="nome">
                    </div>

                    {% comment %} <div class="col-md-4">
                        <select class="form-select" name="tecnologias">
                            <option value="">---------</option>
                            {% for tech in tecnologias %}
                            <option value="{{ tech.id }}">{{ tech }}</option>
                            {% endfor %}
                        </select>
                    </div> {% endcomment %}
                
                <div class="col-md-3">
                    <input type="submit" value="FILTRAR" class="btn btn-lg btn-confirmar">
                </div>
            </div>
            </form>

            <table class="table tabela" cellpadding="20">
                <tr>
                    <th>NOME</th>
          
                    <th>EMAIL</th>
                    <th>TELEFONE</th>

                </tr>

                    {% for i in alunos  %}
                    <tr>
                        <td><a href="{% url 'aluno' i.id%}">{{i.nome}}</a> </td>
                     
                        
                        <td>{{i.email}}</td>
                        <td>{{i.telefone}}</td>
                        {% comment %} <td>
                            <select class="form-select">       
                                {% for tech in empresa.tecnologias.all %}
                                <option>{{ tech }}</option>                    
                                {% endfor %}
                            </select>
                        </td> {% endcomment %}
                        {% comment %} <td>{% if empresa.qtd_vagas %}
                            <img src="{% static 'empresa/img/flag_green.png'%}" alt="">
                            {% else %}
                            <img src="{% static 'empresa/img/flag_red.png'%}" alt="">
                            {% endif %}
                            {{ empresa.qtd_vagas}}
                        </td> {% endcomment %}

                    </tr>
                    {% endfor %}
            </table>
        </div>


        

    </div>
</div>

<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">NOVO ALUNO</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form action='{% url "cadastro_aluno"%}' method="POST" enctype='multipart/form-data'> {% csrf_token %}
        <div class="modal-body">
            <label for="">Nome: </label>
            <div >
                <input type="text" placeholder="Nome do aluno" class="form-control" name="nome">
            </div>
            <br>
            <label for="">Sexo: </label>
            <div >

                <select name="sexo" id="" class='form-control'>
                    <option value="M">MASCULINO</option>
                    <option value="F">FEMININO</option>

                </select>
            </div>
            <br>
            <label for="">Data de Nascimento: </label>
            <div >
                <input type="date" placeholder="Data de nascimento" class="form-control" name="nascimento">
            </div>
            <br>
            <label for="">Email: </label>
            <div >
                <input type="email" placeholder="Email do aluno" class="form-control" name="email">
            </div>
            <br>
            <label for="">Telefone: </label>
            <div >
                <input type="number" placeholder="Telefone do aluno" class="form-control" name="telefone">
            </div>
            <br>
            
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">SAIR</button>
          <button type="submit" class="btn btn-primary">CADASTRAR</button>
        </div>
    </form>
      </div>
    </div>
  </div>
{% endblock conteudo %}

plataforma/templates/dados_aluno.html
{% extends 'base_aluno.html' %}
{% load static %}


{% block conteudo_aluno %}
<br>
<br>
<div class='dados label'>
  <div class='col-md'>
    <label>Nome:</label>
    <input disabled type="text" class="form-control" value="{{aluno.nome}}">
    <br>
   

    <label>Email:</label>
    <input disabled type="text" class="form-control" value="{{aluno.email}}">
    <br>

    <label>Telefone:</label>
    <input disabled type="text" class="form-control" value="{{aluno.telefone}}">
    <br>
    <label>Data de Nascimento:</label>
    <input disabled type="text" class="form-control" value="{{aluno.data_nascimento}}">
    <br>
    
    <label>Sexo:</label>
    <input disabled type="text" class="form-control" value="{{aluno.get_sexo_display}}">
    <br>


    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
        EXCLUIR
      </button>



    <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
        EDITAR
      </button>

  </div>
</div>




        

       
        <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="staticBackdropLabel">EDITAR DE ALUNO</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form action='{% url "editar_aluno" aluno.id %}' method="POST" enctype='multipart/form-data'> {% csrf_token %}
        
                <div class="modal-body">
                    <label for="">Nome: </label>
                    <div >
                        <input type="text" value='{{aluno.nome}}' placeholder="Nome do aluno" class="form-control" name="nome">
                    </div>
        
                    <label for="">Sexo: </label>
                    <div >
                        <select name="sexo" id="" class='form-control'>
                            <option selected value="M">{{aluno.get_sexo_display}}</option>
                            {% comment %} <option value="M">MASCULINO</option>
                            <option value="F">FEMININO</option> {% endcomment %}
                        </select>
                    </div>
        
                    <label for="">Data de Nascimento: </label>
                    <div >
                        <input required type="date" value="{{aluno.data_nascimento}}" placeholder="Data de nascimento" class="form-control" name="nascimento">
                    </div>
        
                    <label for="">Email: </label>
                    <div >
                        <input required type="email" value='{{aluno.email}}' placeholder="Email do aluno" class="form-control" name="email">
                    </div>
              

                    <label for="">Telefone: </label>
                    <div >
                        <input type="number" value='{{aluno.telefone}}' placeholder="Telefone do aluno" class="form-control" name="telefone">
                    </div>

                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">SAIR</button>
                  <button type="submit" class="btn btn-primary">CONFIRMAR</button>
                </div>
            </form>
              </div>
            </div>
          </div>
        

          <!-- Button trigger modal -->

  
  <!-- Modal -->
  <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">CADASTRO DE ALUNO</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form action='{% url "cadastro_aluno" %}' method="POST" enctype='multipart/form-data'> {% csrf_token %}

        <div class="modal-body">
            <label for="">Nome: </label>
            <div >
                <input type="text" placeholder="Nome do aluno" class="form-control" name="nome">
            </div>
            <br>
            <label for="">Sexo: </label>
            <div >

                <select name="sexo" id="" class='form-control'>
                    <option value="M">MASCULINO</option>
                    <option value="F">FEMININO</option>

                </select>
            </div>
            <br>
            <label for="">Data de Nascimento: </label>
            <div >
                <input type="date" placeholder="Data de nascimento" class="form-control" name="nascimento">
            </div>
            <br>
            <label for="">Email: </label>
            <div >
                <input type="email" placeholder="Email do aluno" class="form-control" name="email">
            </div>
            <br>
            <label for="">Telefone: </label>
            <div >
                <input type="number" placeholder="Telefone do aluno" class="form-control" name="telefone">
            </div>
            <br>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">SAIR</button>
          <button type="submit" class="btn btn-primary">CADASTRAR</button>
        </div>
    </form>
      </div>
    </div>
  </div>


  <!--MODAL EXCLUSÃO-->

  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Excluir aluno</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Tem certeza que deseja excluir esse aluno ? 
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">SAIR</button>

          <a href="{% url 'deletar_aluno' aluno.id%}">
          <button type="button" class="btn btn-primary">SIM</button>
            </a>
        </div>
      </div>
    </div>
  </div>


  
  {% endblock conteudo_aluno %}

plataforma/templates/ficha_treino.html
{% extends 'base.html' %}

{% block titulo %}
ALUNOS
{% endblock titulo %}

{% block conteudo %}
<div class="wrapper">
    <div class="box"> 
        <div class="header-box">
            {% if messages %}
                {% for message in messages %}
                    <section class="alert {{message.tags}}">
                        {{message}}
                    </section>
                {% endfor %}
            {% endif %}
       
            <div class='row cd-aluno'>

                <div class='col-md'>
                    <h2 class="titulo">ALUNOS</h2>

            
                

                </div>
            </div>
        </div>
        <div class="borda-box"></div>
        <div class="body-box">
        
            <form action='#' method='GET'> {% csrf_token %}
            <div class="row">
                
                    <div class="col-md-5">
                        <input type="text" placeholder="Busque pelo nome" class="form-control" name="nome">
                    </div>

                    {% comment %} <div class="col-md-4">
                        <select class="form-select" name="tecnologias">
                            <option value="">---------</option>
                            {% for tech in tecnologias %}
                            <option value="{{ tech.id }}">{{ tech }}</option>
                            {% endfor %}
                        </select>
                    </div> {% endcomment %}
                
                <div class="col-md-3">
                    <input type="submit" value="FILTRAR" class="btn btn-lg btn-confirmar">
                </div>
            </div>
            </form>

            <table class="table tabela" cellpadding="20">
                <tr>
                    <th>NOME</th>
                    <th>TREINO</th>
          
                

                </tr>

                    {% for i in alunos  %}
                    <tr>
                        <td>{{i.nome}}</td>
                        <td>
                            <a href="{% url 'ficha_treino_id' i.id%}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-stickies" viewBox="0 0 16 16">
                                <path d="M1.5 0A1.5 1.5 0 0 0 0 1.5V13a1 1 0 0 0 1 1V1.5a.5.5 0 0 1 .5-.5H14a1 1 0 0 0-1-1H1.5z"/>
                                <path d="M3.5 2A1.5 1.5 0 0 0 2 3.5v11A1.5 1.5 0 0 0 3.5 16h6.086a1.5 1.5 0 0 0 1.06-.44l4.915-4.914A1.5 1.5 0 0 0 16 9.586V3.5A1.5 1.5 0 0 0 14.5 2h-11zM3 3.5a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 .5.5V9h-4.5A1.5 1.5 0 0 0 9 10.5V15H3.5a.5.5 0 0 1-.5-.5v-11zm7 11.293V10.5a.5.5 0 0 1 .5-.5h4.293L10 14.793z"/>
                              </svg>
                            </a>
                        </td>
                     
                        
                  
                        {% comment %} <td>
                            <select class="form-select">       
                                {% for tech in empresa.tecnologias.all %}
                                <option>{{ tech }}</option>                    
                                {% endfor %}
                            </select>
                        </td> {% endcomment %}
                        {% comment %} <td>{% if empresa.qtd_vagas %}
                            <img src="{% static 'empresa/img/flag_green.png'%}" alt="">
                            {% else %}
                            <img src="{% static 'empresa/img/flag_red.png'%}" alt="">
                            {% endif %}
                            {{ empresa.qtd_vagas}}
                        </td> {% endcomment %}

                    </tr>
                    {% endfor %}
            </table>
        </div>


        

    </div>
</div>
{% endblock conteudo %}

plataforma/templates/grupo_id.html
{% extends 'base.html' %}

{% block titulo %}
ALUNOS
{% endblock titulo %}

{% block conteudo %}
<div class="wrapper">
    <div class="box"> 
        <div class="header-box">
            {% if messages %}
                {% for message in messages %}
                    <section class="alert {{message.tags}}">
                        {{message}}
                    </section>
                {% endfor %}
            {% endif %}
       
            <div class='row cd-aluno'>

                <div class='col-md'>
                    <h2 class="titulo">Lista de exercícios de {{i}}</h2>

                </div>
                <div class='col-md'>
                    <button type="button" class="btn-confirmar" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                        NOVO EXÉRCICIO 
                      </button>
                

                </div>
            </div>
        </div>
        <div class="borda-box"></div>
        <div class="body-box">
            <table class="table tabela" cellpadding="20">
                <tr>
                    <th>EXÉRCICIO</th>
                    <th>AÇÕES</th>
                </tr>
                    {% for i in exercicios %}
                    <tr>
                        <td>{{i.nome}}</td>
                        <td>
                            <button type="button" class="btn-close" ></button>
                            <button type="button" class="btn-close" ></button>

                        </td> 
                    </tr>
                    {% endfor %}
            </table>
        </div>     
    </div>
</div>

<!-- Button trigger modal -->

  
  <!-- Modal -->
  <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">NOVO EXÉRCICIO</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form action='{% url "cadastro_exercicio"%}' method="POST" enctype='multipart/form-data'> {% csrf_token %}

        <div class="modal-body">
            <label for="">EXERCÍCIO: </label>
            <br>
            <div >
                <input type="text" placeholder="Digite o exercício" class="form-control" name="exercicio">
            </div>
            <br>
            <label for="">MUSCULO: </label>
         
            <div >
           
                <select class="form-select" name='musculo'>       
               
                    <option value='{{i.id}}'>{{ i.nome }}</option>                    
                  
                </select>
            </div>
            
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">SAIR</button>
          <button type="submit" class="btn btn-primary">CADASTRAR</button>
        </div>
    </form>
      </div>
    </div>
  </div>
{% endblock conteudo %}

plataforma/templates/grupos.html
{% extends 'base.html' %}
{% load static %}
{% block conteudo %}

<div class="wrapper">


    <div class='box-home'>
        <div class="header-box">
           <div class='home-titulo'>GYM HARD</div>
           <div class='home-paragrafo'>PERSONAL ONLINE</div>

        </div>

        <div class="body-box">
            
            <div class="row">
                {% for i in grupos %}
                <div class="card card-home" style="width: 15rem;">
                    <a href="{% url 'grupo' i.id%}">
                        <img src="{% static 'plataforma/img/teste.png'%}" class="card-img-top" width='20' height='150' alt="...">

                    </a>
                    <div class="card-body">
                        <h5 class="card-title">{{i.nome}}</h5>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>




{% endblock conteudo %}

plataforma/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}GYM HARD{% endblock titulo %}
{% block conteudo %}

<div class="wrapper">


    <div class='box-home'>
        <div class="header-box">
           <div class='home-titulo'>GYM HARD</div>
           <div class='home-paragrafo'>PERSONAL ONLINE</div>

        </div>

        <div class="body-box">
            <div class="row">
                
                <div class="card card-home" style="width: 15rem;">
                    <a href="{% url 'alunos'%}">
                        <img src="{% static 'plataforma/img/teste.png'%}" class="card-img-top" width='20' height='150' alt="...">

                    </a>
                    <div class="card-body">
                        <h5 class="card-title">ALUNOS</h5>
                    </div>
                </div>
                <div class="card card-home" style="width: 15rem;">
                    <a href="{% url 'alunos'%}">
                        <img src="{% static 'plataforma/img/teste.png'%}" class="card-img-top" width='20' height='150' alt="...">

                    </a>
                    <div class="card-body">
                        <h5 class="card-title">AVALIAÇÃO</h5>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="card card-home" style="width: 15rem;">
                    <a href="{% url 'grupos'%}">
                        <img src="{% static 'plataforma/img/teste.png'%}" class="card-img-top" width='20' height='150' alt="...">

                    </a>
                    <div class="card-body">
                        <h5 class="card-title">EXERCÍCIOS</h5>
                    </div>
                </div>
                <div class="card card-home" style="width: 15rem;">
                    <a href="{% url 'ficha_treino'%}">
                        <img src="{% static 'plataforma/img/teste.png'%}" class="card-img-top" width='20' height='150' alt="...">

                    </a>
                    <div class="card-body">
                        <h5 class="card-title">FICHA DE TREINO</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




{% endblock conteudo %}

plataforma/templates/teste.html
{% extends 'base_aluno.html' %}
{% load static %}

{% block head %}
<link rel='stylesheet' href="{% static 'plataforma/css/teste.css'%}">
{% endblock head %}
{% block conteudo_aluno %}


  
{% endblock conteudo_aluno %}